import { Router, Request, Response } from 'express';
import http from 'http';
import { query } from '../db/connection.js';
import { getContainerIp } from '../sessions/container-manager.js';
import { getConfig } from '../config.js';
import crypto from 'crypto';

export const previewRouter = Router();

// ---------------------------------------------------------------------------
// Signed preview token — proves the URL was generated by the server
// ---------------------------------------------------------------------------

export function signPreviewToken(sessionId: string, port: number): string {
  const secret = getConfig().auth.jwt_secret;
  return crypto
    .createHmac('sha256', secret)
    .update(`preview:${sessionId}:${port}`)
    .digest('hex')
    .slice(0, 32);
}

function verifyPreviewToken(sessionId: string, port: number, token: string): boolean {
  return signPreviewToken(sessionId, port) === token;
}

// ---------------------------------------------------------------------------
// Container IP cache — avoids Docker inspect on every asset request
// ---------------------------------------------------------------------------

const ipCache = new Map<string, { ip: string; expires: number }>();
const IP_CACHE_TTL = 30_000; // 30 seconds

async function getCachedContainerIp(containerId: string): Promise<string | null> {
  const cached = ipCache.get(containerId);
  if (cached && cached.expires > Date.now()) {
    return cached.ip;
  }

  const ip = await getContainerIp(containerId);
  if (ip) {
    ipCache.set(containerId, { ip, expires: Date.now() + IP_CACHE_TTL });
  }
  return ip;
}

// ---------------------------------------------------------------------------
// Session lookup cache — avoids DB query on every asset request
// ---------------------------------------------------------------------------

const sessionCache = new Map<string, { containerId: string; status: string; expires: number }>();
const SESSION_CACHE_TTL = 10_000; // 10 seconds

async function getCachedSession(sessionId: string): Promise<{ containerId: string; status: string } | null> {
  const cached = sessionCache.get(sessionId);
  if (cached && cached.expires > Date.now()) {
    return { containerId: cached.containerId, status: cached.status };
  }

  const result = await query(
    `SELECT container_id, status FROM sessions WHERE id = $1`,
    [sessionId],
  );

  if (result.rows.length === 0) return null;

  const row = result.rows[0];
  sessionCache.set(sessionId, {
    containerId: row.container_id,
    status: row.status,
    expires: Date.now() + SESSION_CACHE_TTL,
  });

  return { containerId: row.container_id, status: row.status };
}

// ---------------------------------------------------------------------------
// Proxy handler — shared by both route patterns
// ---------------------------------------------------------------------------

async function handlePreview(req: Request, res: Response): Promise<void> {
  const sessionId = req.params.sessionId as string;
  const port = req.params.port as string;
  const portNum = parseInt(port, 10);

  if (isNaN(portNum) || portNum <= 0 || portNum > 65535) {
    res.status(400).json({ error: 'Invalid port' });
    return;
  }

  // Validate signed token
  const token = (req.query.token as string) || '';
  if (!verifyPreviewToken(sessionId, portNum, token)) {
    res.status(403).json({ error: 'Invalid or missing preview token' });
    return;
  }

  try {
    const session = await getCachedSession(sessionId);

    if (!session) {
      res.status(404).json({ error: 'Session not found' });
      return;
    }

    if (session.status !== 'active' && session.status !== 'grace') {
      res.status(400).json({ error: 'Session is not active' });
      return;
    }

    const containerIp = await getCachedContainerIp(session.containerId);
    if (!containerIp) {
      res.status(502).json({ error: 'Cannot reach container' });
      return;
    }

    // Build the forwarded path
    const wildcardPath = req.params.path;
    const forwardPath = wildcardPath ? `/${wildcardPath}` : '/';
    const queryEntries = Object.entries(req.query).filter(([k]) => k !== 'token');
    const queryString = queryEntries.length > 0
      ? '?' + queryEntries.map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join('&')
      : '';
    const target = `http://${containerIp}:${portNum}${forwardPath}${queryString}`;

    // Proxy the request
    const proxyReq = http.request(
      target,
      {
        method: req.method,
        headers: {
          ...req.headers,
          host: req.headers.host || '',
        },
      },
      (proxyRes) => {
        res.writeHead(proxyRes.statusCode || 502, proxyRes.headers);
        proxyRes.pipe(res);
      },
    );

    proxyReq.on('error', (err) => {
      console.error(`[Preview] Proxy error for ${sessionId}:${portNum}:`, err.message);
      if (!res.headersSent) {
        res.status(502).json({ error: 'Service not reachable on this port' });
      }
    });

    req.pipe(proxyReq);
  } catch (err) {
    console.error('[Preview] Error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Preview proxy failed' });
    }
  }
}

// Match both /preview/:sessionId/:port and /preview/:sessionId/:port/anything
previewRouter.all('/:sessionId/:port', handlePreview);
previewRouter.all('/:sessionId/:port/{*path}', handlePreview);
